export class ElectricalShort {
  constructor(
    public _id: string,
    public chiildList: any[],
    public dateCreate: string,
    public isChecked: boolean,
    public loadFactor: number,
    public nameplateRating: number,
    public revision: string,
    public scenarioFirstFLA: number,
    public scenarioFirstKVA: number,
    public scenarioFirstKVAR: number,
    public scenarioFirstKW: number,
    public scenarioFirstLoadFactor: number,
    public selectedEquipmentType: string,
    public selectedUnits: string,
    public selectedVoltage: any,
    public totalConectedFla: number,
    public totalConectedKW: number,
    public totalConnectedKVA: number,
    public totalConnectedKVAR: number,
    public totalDemandFLA: number,
    public totalDemandKVA: number,
    public totalDemandKVAR: number,
    public totalDemandKW: number,
    public totalEFF: number,
    public totalPF: number,
  ) { }
}
